name: Release
defaults:
  run:
    working-directory: code-debug
on:
  release:
    types: [published]

jobs:
  release:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node-version: ['18.x']
    runs-on: ${{ matrix.os }}
    steps:
    #
    # Basic Setup
    #
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # - name: Install Module Dependencies
    #   run: npm clean-install --omit=optional
    - name: Install Dependencies
      run: npm install

    #
    # Package and Upload Extension
    #
    # NOTE:
    # The "vscode:prepublish" script in package.json will be executed to compile the extension
    # prior to packaging.
    #
    - name: Package Extension into .vsix file
      id: asset
      shell: bash
      run: >
        npx vsce package;
        echo "vsix_path=$(find . -type f -name '*.vsix')" >> $GITHUB_ENV

    - name: Upload .vsix file to Github as release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.vsix_path }}
        asset_name: ${{ env.vsix_path }}
        asset_content_type: application/zip

    #
    # Publish Extension
    #
    - name: Publish to VSCode Extension Marketplace
      env:
        VSCE_PAT: ${{ secrets.VS_MARKETPLACE_TOKEN }}
      run: npx vsce publish --packagePath ${{ env.vsix_path }}
  
    - name: Publish to Open VSX Registry
      env:
        OVSX_PAT: ${{ secrets.OPEN_VSX_TOKEN }}
      run: npx ovsx publish ${{ env.vsix_path }}
  